## 20191119---3.2_Basic_Operations---QuTip---Qobj()

In [1]:
from qutip import *

In [2]:
import numpy as np

### Quantum Object Class
#### Qobj()

In [3]:
Qobj(4)
# Here the output is 0.0 without any input.....how.?
# based on output, here defined its dimension, or based on input..?

Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[4.]]

In [4]:
np.array(5).ndim

0

### 1D array

In [5]:
shape(np.array([]))

(0,)

In [6]:
np.array([]).ndim

1

In [7]:
Qobj([[]])
# why its not executed but 2D quantum executed....what my mistake was.?
# Here my doubt is - In numpy we have the output even for a single braces but not in Quantum ...why.?
# look above numpy example with dimension as well

Quantum object: dims = [[1], [0]], shape = (1, 0), type = bra
Qobj data =
[]

### 2D array

In [8]:
shape(np.array([[]]))

(1, 0)

In [9]:
np.array([[]]).ndim

2

In [10]:
Qobj([[],[],[]])

Quantum object: dims = [[3], [0]], shape = (3, 0), type = other
Qobj data =
[]

### 3D array

In [11]:
shape(np.array([[[]]]))

(1, 1, 0)

In [12]:
np.array([[[]]]).ndim

3

In [14]:
#Qobj([[[]]])

## As per the output, EXECUTED in the above, what i understood is, QUANTUM consider UPTO 2D only. WHY.?

#### one more example using numpy

In [15]:
a11=[[1,2,3],[4,5,6]]
#a11=np.asarray(a11)
a11=np.array(a11)
a11

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
print("Shape: ",shape(a11))
print("Dim: ",a11.ndim)

Shape:  (2, 3)
Dim:  2


#### Let's try the same input in Quantum

In [17]:
Qobj([[1,2,3],[4,5,6]])

Quantum object: dims = [[2], [3]], shape = (2, 3), type = other
Qobj data =
[[1. 2. 3.]
 [4. 5. 6.]]

In [18]:
Qobj([[1,],[2]])

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [2.]]

In [19]:
Qobj([[1,2,3],[4,5,6],[7,8,9]])

Quantum object: dims = [[3], [3]], shape = (3, 3), type = oper, isherm = False
Qobj data =
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

#### Note - Both matrices are not square and my doubt is, for 2*1 matrix the type shows as KET, for 2*3 matrix the type is OTHER, but in the below 3*3 matrix type is OPER. Why.?
#### if m=n for m*n matrix then type is "OPER"
#### i have to study more on these theoretically from quantum book.

### I understood both Dimension & Shape but not type which is executed in the output and also type is changing in all 4 examples...what is that means - other, ket, oper, bra -.?
- bra-ket are belongs to Dirac Notations which belongs to Hilbert space.........i have to study on those.

In [20]:
np.array([[7],[8],[9]]).ndim

2

In [21]:
np.array([[7,8,9]]).ndim

2

In [22]:
Qobj(np.random.rand(4,4))

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.89098009 0.86739417 0.93215611 0.22880626]
 [0.74611042 0.19383388 0.37939348 0.78613743]
 [0.74998868 0.54173109 0.01843065 0.3746083 ]
 [0.00621868 0.4994533  0.8351828  0.59944588]]

#### -----------End of this Qobj()----------

# Next topic --- Quantum STATES_Operators