# 20191119---QuTip_States_Operators

In [1]:
from qutip import *

In [2]:
import numpy as np

### States - Operators Examples

- Manually specifying the data for each quantum object is inefficient. Even more so when most objects correspond to commonly used types such as the 'ladder operators' of a harmonic oscillator, the 'Pauli spin operators' for a twolevel system, or 'state vectors' such as Fock states. 

- Therefore, QuTiP includes predefined objects for a variety of states: please go to the Qutip documentary page no 14
#### NOTE
- basis command is belongs to - Fock state vector -

##### command 
- basis(N,#m)

##### Input - 
- N = the number of levels in Hilbert space
- =# means optional
- m = the level containing excitation (0, if m is not given)

##### NOTE:
- basis(N,#m)
    - Here 'N' should not be less than 'm'
    - If 'm' is more than 'N' then - ValueError: basis vector index need to be in n <= N-1

In [3]:
basis()

TypeError: basis() missing 1 required positional argument: 'N'

In [4]:
basis(0)

ValueError: basis vector index need to be in n <= N-1

In [5]:
basis(1)

Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[1.]]

In [6]:
basis(2)

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]]

In [7]:
basis(3)

Quantum object: dims = [[3], [1]], shape = (3, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]]

In [8]:
basis(1,0)

Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[1.]]

In [9]:
basis(1,1)

ValueError: basis vector index need to be in n <= N-1

In [12]:
basis(2,0)

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]]

In [13]:
basis(2,1)

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]

In [14]:
basis(2,2)

ValueError: basis vector index need to be in n <= N-1

In [15]:
basis(3,0)

Quantum object: dims = [[3], [1]], shape = (3, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]]

In [16]:
basis(3,1)

Quantum object: dims = [[3], [1]], shape = (3, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [0.]]

In [17]:
basis(3,2)

Quantum object: dims = [[3], [1]], shape = (3, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [1.]]

In [18]:
basis(3,3)

ValueError: basis vector index need to be in n <= N-1

In [19]:
basis(5,2)

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [1.]
 [0.]
 [0.]]

In [20]:
basis(7,4)

Quantum object: dims = [[7], [1]], shape = (7, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]]

## NOTE - something different but interesting with more confusion 
- Let me try to understand first and later i will try to do on this


### ---------------------END----------------------