# Om
# 20191108---3.2_Basic_Operations_on_Quantum_Objects

## QuTiP

### User Guide
- (http://qutip.org/docs/4.1/guide/guide.html)

    -3.2 Basic Operations on Quantum Objects (Upto 20 pages in qutip doc book)
        -3.2.1 First things first
        -3.2.2 The quantum object class
        -3.2.3 Functions operating on Qobj class


### 3.2 Basic Operations on Quantum Objects

#### 3.2.1 First things first
- Warning: Do not run QuTiP from the installation directory.
- To load the qutip modules, we must first call the import statement:

In [1]:
from qutip import *

that will load all of the user available functions. Often, we also need to import the NumPy and Matplotlib libraries
with:

In [2]:
import numpy as np
import matplotlib.pyplot as plt

Note that, in the rest of the documentation, functions are written using -- qutip.module.function() -- notation which
links to the corresponding function in the -- QuTiP API: Functions. -- However, in calling import *, we have already
loaded all of the QuTiP modules. Therefore, we will only need the function name and not the complete path when
calling the function from the interpreter prompt, Python script, or Jupyter notebook.

### 3.2.2 The quantum object class
##### Introduction

- The key difference between classical and quantum mechanics lies in the use of operators instead of numbers as variables.
- Moreover, we need to specify state vectors and their properties. 
- Therefore, in computing the dynamics of quantum systems we need a data structure that is capable of encapsulating the properties of a quantum operator and ket/bra vectors. 
- The quantum object class, qutip.Qobj, accomplishes this using matrix representation.

To begin, let us create a blank Qobj:

In [3]:
Qobj()

Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[0.]]

where we see the blank Qobj object with dimensions, shape, and data. Here the data corresponds to a 1x1- dimensional matrix consisting of a single zero entry.

Hint: By convention, Class objects in Python such as Qobj() differ from functions in the use of a beginning capital letter.

We can create a Qobj with a user defined data set by passing a list or array of data into the Qobj:

In [4]:
# Just Observe the difference between with print() and without
Qobj([[1],[2],[3],[4],[5],[6]])

Quantum object: dims = [[6], [1]], shape = (6, 1), type = ket
Qobj data =
[[1.]
 [2.]
 [3.]
 [4.]
 [5.]
 [6.]]

In [5]:
print(Qobj([[1],[2],[3],[4],[5],[6]]))

Quantum object: dims = [[6], [1]], shape = (6, 1), type = ket
Qobj data =
[[1.]
 [2.]
 [3.]
 [4.]
 [5.]
 [6.]]


In [6]:
Qobj(np.array([[1,2,3,4,5]]))

Quantum object: dims = [[1], [5]], shape = (1, 5), type = bra
Qobj data =
[[1. 2. 3. 4. 5.]]

In [7]:
print(Qobj(np.array([[1,2,3,4,5]])))

Quantum object: dims = [[1], [5]], shape = (1, 5), type = bra
Qobj data =
[[1. 2. 3. 4. 5.]]


Here in the above we can see the dims, shape, type and 
- what all these called.? and why these are different from actual python.?

In [8]:
# random
Qobj(np.random.rand(5,5))

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = False
Qobj data =
[[0.71262057 0.64909788 0.49211159 0.53010348 0.54372417]
 [0.88581286 0.71637059 0.57209697 0.92517005 0.846643  ]
 [0.73628169 0.2519392  0.68319367 0.72000658 0.60775852]
 [0.66024527 0.25705422 0.176366   0.74336251 0.35314653]
 [0.08411413 0.37424147 0.65574553 0.33166815 0.83620843]]

Here 
- What is type called OPERATOR ?
- What is isherm and is False ?

Notice how both the dims and shape change according to the input data. Although dims and shape appear to have the same function, the difference will become quite clear in the section on tensor products and partial traces.

Note: If you are running QuTiP from a python script you must use the print function to view the Qobj attributes.

Next topic is about 
- Quantum States and Quantum Operators (States and Operators)